package vista.usuario;

import controlador.usuario.Ctrl_Usuario_Nuevo;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.usuario.Usuario;
import modelo.usuario.UsuarioDAOImp_Nuevo;
import modelo.usuario.usuarioDAO_Nuevo;

/**
 *
 * @author Guicho
 */
public class InterNuevoUsuario extends javax.swing.JInternalFrame {

    int obtenerIdCategoria = 0;

    public InterNuevoUsuario() {
        initComponents();
        this.setSize(new Dimension(400, 300));
        this.setTitle("Nuevo Usuario");

        txt_password.setVisible(true);
        txt_password_visible.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        jButton_guardar = new javax.swing.JButton();
        txt_telefono = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        checkBox_ver_clave = new javax.swing.JCheckBox();
        txt_password_visible = new javax.swing.JTextField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nuevo Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Apellido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Teléfono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(35, 44, 92));
        txt_nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, -1));

        txt_apellido.setBackground(new java.awt.Color(35, 44, 92));
        txt_apellido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        txt_usuario.setBackground(new java.awt.Color(35, 44, 92));
        txt_usuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        jButton_guardar.setBackground(new java.awt.Color(75, 70, 132));
        jButton_guardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, 30));

        txt_telefono.setBackground(new java.awt.Color(35, 44, 92));
        txt_telefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));

        txt_password.setBackground(new java.awt.Color(35, 44, 92));
        txt_password.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, 25));

        checkBox_ver_clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBox_ver_claveMouseClicked(evt);
            }
        });
        getContentPane().add(checkBox_ver_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 20));

        txt_password_visible.setBackground(new java.awt.Color(35, 44, 92));
        txt_password_visible.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_password_visible.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_password_visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, 25));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:
        //Validar campos vacios
if (txt_nombre.getText().isEmpty() || txt_apellido.getText().isEmpty() || txt_usuario.getText().isEmpty() || txt_password.getText().isEmpty() || txt_telefono.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor complete todos los campos");
    } else {
        //Validar usuario registrado
        Usuario usuario = new Usuario();
        usuarioDAO_Nuevo usuarioDAO_Nuevo = new UsuarioDAOImp_Nuevo();// instancia de UsuarioDAOImp
        Ctrl_Usuario_Nuevo ctrl_Usuario_Nuevo = new Ctrl_Usuario_Nuevo(usuarioDAO_Nuevo); // instancia de Ctrl_Usuario
        //Enviamos la información a la BD
        if (!ctrl_Usuario_Nuevo.existeUsuario(txt_usuario.getText().trim())) {
            usuario.setNombre(txt_nombre.getText().trim());
            usuario.setApellido(txt_apellido.getText().trim());
            usuario.setUsuario(txt_usuario.getText().trim());
            usuario.setPassword(txt_password.getText().trim());
            usuario.setTelefono(txt_telefono.getText().trim());
            usuario.setEstado(1);

            if (ctrl_Usuario_Nuevo.guardar(usuario)) { // pasar instancia de UsuarioDAO a guardar()
                JOptionPane.showMessageDialog(null, "Usuario registrado");
                //Mëtodo limpiar
                this.limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error, el usuario ya está registrado");
        }
    }
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void checkBox_ver_claveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBox_ver_claveMouseClicked
        // TODO add your handling code here:
        /*
        if (checkBox_ver_clave.isSelected() == true) {
            String pass = "";
            char[] passwordIngresado = txt_password.getPassword();
            for (int i = 0; i < passwordIngresado.length; i++) {
                pass += passwordIngresado[i];
            }
            txt_password_visible.setText(pass);
            txt_password.setVisible(false);
            txt_password_visible.setVisible(true);
        } else {
            String passwordIngresado = txt_password_visible.getText().trim();
            txt_password.setText(passwordIngresado);
            txt_password.setVisible(true);
            txt_password_visible.setVisible(false);
        }
         */

        // TODO add your handling code here:
        if (checkBox_ver_clave.isSelected() == true) {
            mostrarContrasena();
        } else {
            ocultarContrasena();
        }


    }//GEN-LAST:event_checkBox_ver_claveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBox_ver_clave;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_password_visible;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

    //Método para limpiar formulario
    private void limpiarCampos() {
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_usuario.setText("");
        txt_telefono.setText("");
        txt_password.setText("");
    }

    private void mostrarContrasena() {
        String pass = "";
        char[] passwordIngresado = txt_password.getPassword();
        for (int i = 0; i < passwordIngresado.length; i++) {
            pass += passwordIngresado[i];
        }
        txt_password_visible.setText(pass);
        txt_password.setVisible(false);
        txt_password_visible.setVisible(true);
    }

    private void ocultarContrasena() {
        String passwordIngresado = txt_password_visible.getText().trim();
        txt_password.setText(passwordIngresado);
        txt_password.setVisible(true);
        txt_password_visible.setVisible(false);
    }

}
